site_name: Alogrithm Archive
theme:
    name: "gitbook"
    custom_dir: "theme_overrides/"
extra_javascript:
    - "site.js"
    - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
    - "site.css"
    - "pygments.css"
markdown_extensions:
    - "language_switch"
    - "fenced_code"
    - "codehilite":
          linenums: true
    - "pymdownx.arithmatex"
plugins:
    - "codeimport"
docs_dir: "contents/"
nav:
    - "Introduction": "introduction/introduction.md"
    - "How To Contribute": "how_to_contribute/how_to_contribute.md"
    - "Data Structures":
          - "Data Structures": "data_structures/data_structures.md"
          - "Stacks and Queues": "stacks_and_queues/stacks_and_queues.md"
    - "Mathematical Background":
          - "Mathematical Background": "mathematical_background/mathematical_background.md"
          - "Complexity Notation": "notation/notation.md"
          - "Bit Logic": "bitlogic/bitlogic.md"
          - "Taylor Series": "taylor_series_expansion/taylor_series_expansion.md"
    - "Sorting and Searching":
          - "Sorting and Searching": "sorting_and_searching/sorting_and_searching.md"
          - "Bubble Sort": "bubble_sort/bubble_sort.md"
          - "Bogo Sort": "bogo_sort/bogo_sort.md"
    - "Tree Traversal": "tree_traversal/tree_traversal.md"
    - "Euclidean Algorithm": "euclidean_algorithm/euclidean_algorithm.md"
    - "Monte Carlo": "monte_carlo_integration/monte_carlo_integration.md"
    - "Matrix Methods":
          - "Matrix Methods": "matrix_methods/matrix_methods.md"
          - "Gaussian Elimination": "gaussian_elimination/gaussian_elimination.md"
          - "Thomas Algorithm": "thomas_algorithm/thomas_algorithm.md"
    - "Computational Geometry":
          - "Computational Geometry": "computational_geometry/computational_geometry.md"
          - "Gift Wrapping":
                - "Gift Wrapping": "gift_wrapping/gift_wrapping.md"
                - "Jarvis March": "jarvis_march/jarvis_march.md"
                - "Graham Scan": "graham_scan/graham_scan.md"
    - "FFT": "cooley_tukey/cooley_tukey.md"
    - "Decision Problems":
          - "Decision Problems": "decision_problems/decision_problems.md"
          - "Stable Marriage Problem": "stable_marriage_problem/stable_marriage_problem.md"
    - "Differential Equation Solvers":
          - "Differential Equation Solvers": "differential_equations/differential_equations.md"
          - "Forward Euler Method": "forward_euler_method/forward_euler_method.md"
    - "Physics Solvers":
          - "Physics Solvers": "physics_solvers/physics_solvers.md"
          - "Verlet Integration": "verlet_integration/verlet_integration.md"
          - "Quantum Systems":
                - "Quantum Systems": "quantum_systems/quantum_systems.md"
                - "Split-Operator Method": "split-operator_method/split-operator_method.md"
    - "Data Compression":
          - "Data Compression": "data_compression/data_compression.md"
          - "Huffman Encoding": "huffman_encoding/huffman_encoding.md"
    - "Quantum Information": "quantum_information/quantum_information.md"
